services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
    - 127.0.0.1:35655:8000
    restart: unless-stopped
  encryptednotes:
    build: ./encryptednotes
    container_name: encryptednotes
    ports:
    - 127.0.0.1:42817:8000
    restart: unless-stopped
  examnotes:
    build: ./examnotes
    container_name: examnotes
    ports:
    - 127.0.0.1:42422:8000
    restart: unless-stopped
  examportal:
    build: ./examportal
    container_name: examportal
    depends_on:
    - examportal-db
    environment:
      DBHOST: examportal-db
      DBNAME: examportal
      DBPASS: ${DB_PASS}
      DBUSER: root
    ports:
    - 127.0.0.1:33513:80
    restart: unless-stopped
  examportal-db:
    command:
    - --default-authentication-plugin=mysql_native_password
    container_name: examportal-db
    environment:
      MYSQL_DATABASE: examportal
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    image: mysql
    restart: unless-stopped
    volumes:
    - ./examportal/db/init:/docker-entrypoint-initdb.d
    - ./examportal/db/data:/var/lib/mysql
version: '3'
